env:
  global:
    - CXX=g++-4.8
    - HAZELCAST_PORT=5701
    - HAZELCAST_HOST=localhost

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run -d -p 5701:5701 hazelcast/hazelcast;
    fi

# Do not insert any code under here without making sures it's in common build first
language: node_js

services:
  - docker

plugins:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "10"

matrix:
  include:
    - node_js: "10"
      os: osx
    - node_js: "10"
      os: linux

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run test;
    fi
  - curl -o package.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io/v4/scripts/connector/package-connector.sh
  - chmod 555 package.sh
  - ./package.sh

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: ${GITHHUB_TOKEN}
    file_glob: true
    file:
      - "build/*.tar.gz"
      - "build/*.zip"
    on:
      tags: true

after_deploy:
  - curl -o test.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io/v4/scripts/connector/test-connector.sh
  - chmod 555 test.sh
  - ./test.sh

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
